# Generated by Django 5.0.1 on 2024-02-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('DNI', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('FirstSurname', models.CharField(max_length=100)),
                ('SecondSurname', models.CharField(max_length=100)),
                ('BirthDate', models.DateField()),
                ('StartedDate', models.DateField()),
                ('DismissalDate', models.DateField()),
                ('RetirementDate', models.DateField()),
            ],
        ),
    ]
