# Generated by Django 5.0.1 on 2024-02-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
    ]
