# Generated by Django 5.0.1 on 2024-02-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresapp', '0002_rename_employees_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DismissalDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='RetirementDate',
            field=models.DateField(blank=True),
        ),
    ]
