# Generated by Django 5.0.1 on 2024-02-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresapp', '0003_alter_employee_dismissaldate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DismissalDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='RetirementDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
